services:
  - type: web
    name: price-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_USER_ID
        sync: false
      - key: HTTP_PROXY
        sync: false
      - key: HTTPS_PROXY
        sync: false
      - key: DEFAULT_COUNTRIES
        value: us,de,fr,it,es,uk,hk,kz
      - key: DEFAULT_BASE_CCY
        value: USD
      - key: GLOBAL_DELAY_MIN
        value: "6.0"
      - key: GLOBAL_DELAY_MAX
        value: "12.0"
      - key: DEBUG_HTML
        value: "0"
      - key: DEBUG_HTML_LEN
        value: "800"
      - key: COOLDOWN_SECONDS
        value: "120"
      - key: REQUEST_TIMEOUT
        value: "35"
